FROM opensearchproject/opensearch-dashboards:latest

COPY --chown=opensearch-dashboards:opensearch-dashboards opensearch_dashboards.yml /usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
